version: 'versions: [ "3.9" ]'

services:
  pgdb:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    volumes:
      - ./docker/local_pgdata:/var/lib/postgresql/data
  adminer:
    image: dockette/adminer
    ports:
      - 8888:80
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
       PGADMIN_DEFAULT_EMAIL: "pgadmin@codepruner.com"
       PGADMIN_DEFAULT_PASSWORD: "pgadminP@ssw0rd!"