import { prismaClient } from "@/utils/prismaClient"
import { PartnersPage } from "./PartnersPage"

export const metadata = {
    title: 'Partners',
    description: 'Generated by create next app',
}

export default async function Page({searchParams: {search = ''}}) {
    const searchLike = '%' + search.replace(/\s+/g, '%') + '%'
    const partners = await prismaClient.$queryRaw`
        SELECT p.*, s.name as sex FROM partners p
        JOIN resources_sex s on "sexId" = s.id
        WHERE CONCAT(p.name, ' ', p.surname, ' ', p.email, ' ', p.phone) LIKE ${searchLike}
        LIMIT 20
    `
    return (
        <PartnersPage {...{partners, searchQuery: search}} />
    )
}